service: root
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.8
  region: ap-south-1

# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
        - Effect: "Allow"
          Action:
            - "lambda:*"
            
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
              - "Ref" : "ServerlessDeploymentBucket"
              - "/*"
functions:
  hello:
    handler: handler.hello
