provider:
  name: aws
  iam:
    role: arn:aws:iam::237918227349:role/jenkins-instance-role
      statements:
        - Effect: 'Allow'
              Action: 
                 - lambda:Get*
                 - lambda:List*
                 - lambda:CreateFunction
                 - lambda:DeleteFunction
                 - lambda:CreateFunction
                 - lambda:DeleteFunction
                 - lambda:UpdateFunctionConfiguration
                 - lambda:UpdateFunctionCode
                 - lambda:PublishVersion
                 - lambda:CreateAlias
                 - lambda:DeleteAlias
                 - lambda:UpdateAlias
                 - lambda:AddPermission
                 - lambda:RemovePermission
                 - lambda:InvokeFunction
	      Resource: '*'
      managedPolicies:
        - 'arn:aws:iam::237918227349:user/*'
      permissionsBoundary: arn:aws:iam::237918227349:policy/boundaries
      tags:
        key: value
    deploymentRole: arn:aws:iam::237918227349:role/demo			 
